---
title: "R opgraven Les 25-04-218"
author: "Rinze-Pieter Jonker & Jouke Profijt"
date: "25 april 2018"
output: pdf_document
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = F}
rm(list=ls())
```

## 1.0 Experiment
[1].  R, r & m

[2].  [https://link.springer.com/referenceworkentry/10.1007%2F978-1-4419-9863-7_382](https://link.springer.com/referenceworkentry/10.1007%2F978-1-4419-9863-7_382).
      
      Uit deze bron kunnen we halen dat de formule die wij gebruiken linear is.

[3].  Zie ModelOpgave3.png

[4].  De return van het model is dR, dit is namelijk de hoeveelhied rna over de verschillende tijd punten. 


## 2.0 Programmeer opdracht:

```{r}
library(deSolve)

time <- seq(0, 30, by = 1)
para <- c(r = 0.2, m = 20)
state <- c(R = 100)

Calculate.mRNA <- function(time, R, para){
  with(as.list(c(para)),{
    dR <- -r * R + m
    return(list(c(dR)))
  }
       )
  
}

result <- ode(time = time,
              y = state,
              parms = para,
              func = Calculate.mRNA,
              method = "euler")

# parameters verandert waardoor je een toenemende hoeveelheid mRNA krijgt
para <- c(r = 0.2, m = 22)
result_increasing <- ode(time = time,
                         y = state,
                         parms = para,
                         func = Calculate.mRNA,
                         method = "euler")
# parameters verandert waardoor je een afnemende hoeveelheid mRNA krijgt
para <- c(r = 0.2, m = 18)
result_decreasing <- ode(time = time,
                         y = state,
                         parms = para,
                         func= Calculate.mRNA,
                         method = "euler")

plot(result, result_increasing, result_decreasing,
     main = "Hoeveelheid mRNA transcripts over de tijd",
     ylab = "Hoeveelheid mRNA transcripts",
     xlab = "Tijdpunten",
     ylim = c(85,115))

legend("topright",
       c("[A]. Steady-state", "[B]. Toenemend", "[C]. Afnemend"),
       col = c("black", "red", "green"), lty = 1:3)
```
