---
title: "Les 1 (24-04-2018)"
author: "Rinze-Pieter Jonker & Jouke Profijt"
date: "25 april 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = F} 
rm(list=ls())
```



##1.0 Experiment

[1].  Het toe te voegen volume (hier 10)
      Het percentage wat er af gaat (hier ook weer 10)
      
[2].  Het Volume

[3].  0

[4].  0.30

[5].  afgerond op 28

[6].  wanneer dY = 0


## 2.0 Programmeer opdracht

```{r}
library(deSolve)

para <- c(add = 10, pV = 0.1)
state <- c(volume = 0)
times <- seq(0, 100,  by = 1)

Calculate.Balans <- function(time, y, para){
 with(as.list(c(para)),{
         dY <- add - pV * (y+add)
         return(list(c(dY)))
       }
       )
  
}
out <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

head(out)
plot(out,
     main = "Volume over tijd",
     ylab = "Volume",
     xlab = "Tijdpunten")

```
\pagebreak

[1].  parameters verandert naar 5 verschillende

      - normaal
      - minder per keer toevoegen
      - meer per keer toevoegen
      - hoger percentage er van af
      - lager percentage er van af
      
```{r}
para <- c(add = 5, pV = 0.1)
state <- c(volume = 0)
times <- seq(0, 100,  by = 1)

out2 <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

para <- c(add = 15, pV = 0.1)
state <- c(volume = 0)
times <- seq(0, 100,  by = 1)

out3 <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

para <- c(add = 10, pV = 0.2)
state <- c(volume = 0)
times <- seq(0, 100,  by = 1)

out4 <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

para <- c(add = 10, pV = 0.05)
state <- c(volume = 0)
times <- seq(0, 100,  by = 1)

out5 <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

plot(out, out2, out3, out4, out5,
     main = "Volume over tijd",
     ylab = "Volume",
     xlab = "Tijdpunten")

legend("bottomright",
       c("normaal", "minder toevoeging", 
         "meer toevoeging", "lager percentage", "hoger percentage"),
       lty = 1:5,
       col = c("black", "red", "green", "dark blue", "cyan"))

```

\pagebreak

[2].  initiele waardes aangepast naar 3 verschillende

      - normaal
      - hoger dan normaal
      - lager dan normaal
      
```{r}
para <- c(add = 10, pV = 0.1)
state <- c(volume = 10)
times <- seq(0, 100,  by = 1)

init1 <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

para <- c(add = 10, pV = 0.1)
state <- c(volume = -10)
times <- seq(0, 100,  by = 1)

init2 <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

plot(out, init1, init2,
     main = "Volume over tijd",
     ylab = "Volume",
     xlab = "Tijdpunten")

legend("bottomright",
       c("normaal", "initiele waarde omhoog gezet", "initiele waarde omlaag gezet"),
       lty = 1:3,
       col = c("black", "red", "green"))
```

\pagebreak

[3].  de tijdpunten verandert

      - normaal
      - meer tijdunten
      - minder tijdpunten
      
```{r}
para <- c(add = 10, pV = 0.1)
state <- c(volume = 0)
times <- seq(0, 50,  by = 1)

ti1 <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

para <- c(add = 10, pV = 0.1)
state <- c(volume = 0)
times <- seq(0, 150,  by = 1)

ti2 <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

plot(ti1,
     main = "Volume over tijd",
     ylab = "Volume",
     xlab = "Tijdpunten",
     sub = "met 50 tijdpunten",
     xlim = c(0, 200))

plot(out,
     main = "Volume over tijd",
     ylab = "Volume",
     xlab = "Tijdpunten",
     sub = "met 100 tijdpunten",
     xlim = c(0, 200))

plot(ti2,
     main = "Volume over tijd",
     ylab = "Volume",
     xlab = "Tijdpunten",
     sub = "met 150 tijdpunten",
     xlim = c(0, 200))
```

\pagebreak

[4].    Het model verandert van (y + a) naar y verandert

```{r}
para <- c(add = 10, pV = 0.1)
state <- c(volume = 0)
times <- seq(0, 100,  by = 1)

Calculate.Balans <- function(time, y, para){
 with(as.list(c(para)),{
         dY <- add - pV * y
         return(list(c(dY)))
       }
       )
}

new_out <- ode(time = times,
           y = state,
           parms = para,
           func = Calculate.Balans,
           method = "euler")

plot(out , new_out,
     main = "Volume over tijd",
     ylab = "Volume",
     xlab = "Tijdpunten")
legend("bottomright",
       c("model met (Y + A)", "model met Y"),
       col = c("black", "red"),
       lty = 1:2)
```

## 3.0 Oefenen met de tutorial

[1].    Yini en de parms

[2].    0

[3].    1 t/m 6
