---
title: "Weekopdrachten_Week3"
author: "Rinze-Pieter Jonker & Jouke Profijt"
date: "May 22, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F, warning=F}
rm(list = ls())
library(deSolve)
```

# __ Assignment 1. assess model validity__


```{r}
data <- read.csv("MPL.csv", header = T, na.strings = "NA")

medians <- aggregate(data[,c("MPL_conc","mRNA","Free_receptor")],list(data$dose,data$time), median, na.rm=T)
names(medians)[1:2] <- c("dose","time")

```

```{r}
#tijd is voor zeven dagen, 24 * 7
time <- seq(0, 168, 1)

#parameters
para2 <- c(ksrm = 2.9,
          IC50rm = 26.2,
          kdrm = 0.612,
          ksr = 3.22,
          kre = 0.57,
          kon = 0.00329,
          kdr = 0.0572,
          kt = 0.63,
          Rf = 0.49,
          D = (14.59 * 1000) / 371.471 ) # verander hier de 20 om de D waarde aan te passen
                                      # dit zet het om van ng/ml naar nmol/l

para <- c(ksrm = 2.9,
          IC50rm = 26.2,
          kdrm = 0.612,
          ksr = 3.22,
          kre = 0.57,
          kon = 0.00329,
          kdr = 0.0572,
          kt = 0.63,
          Rf = 0.49,
          D = (39.925 * 1000) / 371.471 ) # verander hier de 20 om de D waarde aan te passen
                                      # dit zet het om van ng/ml naar nmol/l

#startwaardes
state <- c(Rmo = 4.740, 
           Ro = 267,
           DR = 0,
           DRN = 0)

cocortisocosteroid.model <- function(time, para, state){
    with(as.list(c(state, para)),{
        dmRNA <- ksrm * (1 - DRN / (IC50rm + DRN)) - kdrm * Rmo
        dR <- ksr * Rmo + Rf * kre * DRN - kon * D * Ro - kdr * Ro
        dDR <- kon * D * Ro - kt * DR
        dDRN <- kt * DR - kre * DRN
        
        return(list(c(dmRNA, dR, dDR, dDRN)))
        }
    )
}

out <- ode(y = state,
           times = time,
           parms = para,
           func = cocortisocosteroid.model,
           method = "euler")

out2 <- ode(y = state,
           times = time,
           parms = para2,
           func = cocortisocosteroid.model,
           method = "euler")
```


```{r}

# Concentratie mRNAR
plot(out[,1], out[,2],
     type = "l", 
     xlab = "Tijd in uur",
     ylab = "fmol/g mRNAR",
     main = "Concentratie mRNAR over 168 uur")
lines(out2[,1], out2[,2],
      col = "red")
lines(medians[,2], medians[,4],
      col = "blue",
      type = "p",
      lty = 3)
legend("topright",
       c("Dose van 39.925 ng/ml", "Dose van 14.59 ng/ml", "medians"),
       col = c("black", "red", "blue"),
       lty = c(1, 1, NA),
       pch = c(NA, NA, 1))

# Vrije glucocorticoid receptoren
plot(out[,1], out[,3], 
     type = "l",
     xlab = "Tijd in uur",
     ylab = "fmol/mg vrije glucocorticoid receptoren",
     main = "Concentratie vrije glucocorticoid receptoren over 168 uur")
lines(out2[,1], out2[,3],
      col = "red")
lines(medians[,2], medians[,3],
      col = "blue",
      type = "p",
      lty = 3)
legend("topright",
       c("Dose van 39.925 ng/ml", "Dose van 14.59 ng/ml", "medians"),
       col = c("black", "red", "blue"),
       lty = c(1, 1, NA),
       pch = c(NA, NA, 1))

# Dichtheid MPL-receptoren
# kon geen data hiervan vinden
# plot van para 2 doet raar
plot(out[,1], out[,4], 
     type = "l",
     xlab = "Tijd in uur",
     ylab = "fmol/mg MPL-receptor complex",
     main = "Dichtheid van het MPL-receptoren complex over 168 uur",
     ylim = c(0,200))
lines(out2[,1], out2[,3],
      col = "red")
legend("topright",
       c("Dose van 39.925 ng/ml", "Dose van 14.59 ng/ml"),
       col = c("black", "red"),
       lty = 1)

# MPL receptoren in de nucleus
plot(out[,1], out[,5], 
     type = "l",
     xlab = "Tijd in uur", 
     ylab = "fmol/mg MPL-receptoren complex",
     main = "Hoeveelheid MPL-receptoren complex in de nucleus over 168 uur",
     ylim = c(0,200))
lines(out2[,1], out2[,3],
      col = "red")
lines(medians[,2], medians[,5],
      col = "blue",
      type = "p",
      lty = 3)
legend("topright",
       c("Dose van 39.925 ng/ml", "Dose van 14.59 ng/ml", "medians"),
       col = c("black", "red", "blue"),
       lty = c(1, 1, NA),
       pch = c(NA, NA, 1))
```
\pagebreak

# __Assigment 2. simulate scenario’s__
```{r}
# waarden voor de normale simulaties
# tijdspan
time <- seq(0, 48, 1)

#parameters
para <- c(ksrm = 2.9,
          IC50rm = 26.2,
          kdrm = 0.612,
          ksr = 3.22,
          kre = 0.57,
          kon = 0.00329,
          kdr = 0.0572,
          kt = 0.63,
          Rf = 0.49,
          D = (20 * 1000) / 371.471 ) # verander hier de 20 om de D waarde aan te passen
                                      # dit zet het om van ng/ml naar nmol/l

#startwaardes
state <- c(Rmo = 4.740, 
           Ro = 267,
           DR = 0,
           DRN = 0)

cocortisocosteroid.model <- function(time, para, state){
    with(as.list(c(state, para)),{
        dmRNA <- ksrm * (1 - DRN / (IC50rm + DRN)) - kdrm * Rmo
        dR <- ksr * Rmo + Rf * kre * DRN - kon * D * Ro - kdr * Ro
        dDR <- kon * D * Ro - kt * DR
        dDRN <- kt * DR - kre * DRN
        
        return(list(c(dmRNA, dR, dDR, dDRN)))
        }
    )
}

cocortisocosteroid.model.aangepast <- function(time, para, state){
    with(as.list(c(state, para)),{
        dmRNA <- ksrm * (1 - DRN / (IC50rm + DRN)) - kdrm * Rmo
        dR <- ksr * Rmo + Rf * kre * DRN - kon * D * Ro - kdr * Ro
        dDR <- kon * D * Ro - kt * DR
        dDRN <- kt * DR - kre * DRN
        
        return(list(c(dmRNA, dR, dDR, dDRN)))
        }
    )
}

normaal <- ode(y = state,
               times = time,
               parms = para,
               func = cocortisocosteroid.model,
               method = "euler")

aangepast <- ode(y = state,
                 times = time,
                 parms = para,
                 func = cocortisocosteroid.model,
                 method = "euler")
```
